name: Tests

on:
  pull_request:
  push:    
    branches:      
      - main

jobs:
  integration_tests:
    # Will not run if the event is a PR to bump-v* (so a pre-release PR)
    # Will still run for each push to bump-v*
    if: github.event_name != 'pull_request' || !startsWith(github.base_ref, 'bump-v')
    name: integration-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal